version: 1
policy:
  pullRequests: public
tasks:
  - taskId: {$eval: as_slugid("decision")}
    provisionerId: aws-provisioner-v1
    workerType: github-worker
    retries: 5
    extra:
      github:
        env: true
        events:
          - push
      foo: {$eval: event}
    scopes:
      - assume:repo:github.com/glandium/git-cinnabar:decision-task
    payload:
      maxRunTime: 3600
      image: python:2.7
      features:
        taskclusterProxy: true
      env:
        TASKCLUSTER_PROXY: 1
      command:
        - sh
        - '-c'
        - >-
          git clone -n {{ event.head.repo.url }} repo &&
          git -c advice.detachedHead=false -C repo checkout {{ event.head.sha }} &&
          virtualenv venv &&
          venv/bin/pip install requests &&
          venv/bin/python repo/CI/decision.py
    created: {$fromNow: ''}
    deadline: {$fromNow: '2 hours'}
    expires: {$fromNow: '26 weeks'}
    metadata:
      name: decision task
      description: '{{ event.head.repo.name }} decision task'
      owner: a@b.c
      source: https://goo.com
