#!/bin/sh
''':'
py="$GIT_CINNABAR_PYTHON"
if test -z "$py"; then
  for py in python3 python2.7 python2; do
    "$py" -c "from mercurial import hg" >/dev/null 2>&1 && break
    py=
  done
fi
if test -z "$py"; then
  for py in python3 python2.7 python2; do
    command -v "$py" > /dev/null && break
    py=python3
  done
fi
exec "$py" "$0" "$@"
exit 1
'''

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__)))
sys.path.append(os.path.join(os.path.dirname(__file__), 'pythonlib'))

from cinnabar.cmd import CLI
from cinnabar.util import run


if __name__ == '__main__':
    func, args = CLI.prepare(sys.argv[1:])
    run(func, args)
