#!/usr/bin/env python2.7

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__)))
sys.path.append(os.path.join(os.path.dirname(__file__), 'pythonlib'))

from cinnabar.cmd import CLI
from cinnabar.util import run


if __name__ == '__main__':
    func, args = CLI.prepare(sys.argv[1:])
    run(func, args, getattr(func, 'python3', True))
