name: cargo package
on:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'git-core'
      - '.github/workflows/cargo-package.yml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'git-core'
      - '.github/workflows/cargo-package.yml'
jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [1.85.1]
        include:
          - os: windows-latest
            toolchain: 1.85.1-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            patch
        if: runner.os == 'Windows'
      - name: Update PATH
        run: |
          (Resolve-Path c:/msys64/mingw64/bin).Path >> $Env:GITHUB_PATH
        if: runner.os == 'Windows'
      - run: cargo package
